Shuffle

In [1]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])

np.random.shuffle(arr)
print(arr)

[1 3 4 2 5]


Unique

In [5]:
arr2 = np.array([6, 7, 8, 9, 10,3,4,5,6,7,8,9,10,2,3,4,4,6])
print("Original array 2:", arr2)
y = np.unique(arr2)
print("Unique values of arr2:", y)

Original array 2: [ 6  7  8  9 10  3  4  5  6  7  8  9 10  2  3  4  4  6]
Unique values of arr2: [ 2  3  4  5  6  7  8  9 10]


In [6]:
z = np.unique(arr2, return_index=True, return_counts=True, return_inverse=True)
print(z)
#return_counts: returns the number of times each unique item appears in the original array.
#return_index: returns the indices of the first occurrences of the unique values in the original array
#return_inverse: returns the indices to reconstruct the original array from the unique array.


(array([ 2,  3,  4,  5,  6,  7,  8,  9, 10]), array([13,  5,  6,  7,  0,  1,  2,  3,  4], dtype=int64), array([4, 5, 6, 7, 8, 1, 2, 3, 4, 5, 6, 7, 8, 0, 1, 2, 2, 4], dtype=int64), array([1, 2, 3, 1, 3, 2, 2, 2, 2], dtype=int64))


Resize

In [7]:
arr2 = np.array([6, 7, 8, 9, 10])
print("Original array 2:", arr2)
i = np.resize(arr2, (3,4))
print("Resized array:", i)

Original array 2: [ 6  7  8  9 10]
Resized array: [[ 6  7  8  9]
 [10  6  7  8]
 [ 9 10  6  7]]


Flatten

 orders in flatten : 
 'C' means to flatten in row-major (C-style) order. 
 'F' means to flatten in column-major (Fortran-style) order.
'A' means to flatten in column-major order if the array is Fortran contiguous in memory, row-major order otherwise.
'K' means to flatten the array in the order the elements occur in memory. The default is 'C'. 

In [11]:
r = np.array([[1, 2, 3], [4, 5, 6]])
f = r.flatten(order='F')
print(f)
# orders in flatten :
c = r.flatten(order='C')
print(c)
a = r.flatten(order='A')
print(a)
k = r.flatten(order='K')
print(k)

[1 4 2 5 3 6]
[1 2 3 4 5 6]
[1 2 3 4 5 6]
[1 2 3 4 5 6]


In [ ]:
# ravel is used to create a flattened array. It returns a flattened one-dimensional array and is a method of ndarray class.
# The difference between flatten and ravel is that flatten always returns a copy of the original array, while ravel returns a flattened array as a view of the original array whenever possible.
# orders in ravel :
o = np.array([[1, 2, 3], [4, 5, 6]])
v = o.ravel(order='F')
print(v)

[1 4 2 5 3 6]
