7 arithmatic operations add,sub,mul,div,mod,power,reciprocal

1D array

In [1]:
import numpy as np
var = np.array([1,2,3,4])
var_add= var+3
print(var_add)

[4 5 6 7]


In [6]:
import numpy as np
var = np.array([1,2,3,4])
var_sub= var-3
print(var_sub)

[-2 -1  0  1]


In [7]:
import numpy as np
var = np.array([1,2,3,4])
var_mul= var*3
print(var_mul)

[ 3  6  9 12]


In [8]:
import numpy as np
var = np.array([1,2,3,4])
var_div= var/3
print(var_div)

[0.33333333 0.66666667 1.         1.33333333]


In [9]:
import numpy as np
var = np.array([1,2,3,4])
var_mod= var%3
print(var_mod)

[1 2 0 1]


In [12]:
var = np.array([1,2,3,4])
power= var ** 2
print(power)

[ 1  4  9 16]


2D array

In [2]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])
add = arr1 + arr2
print(add)


[ 6  8 10 12]


another add method

In [10]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])
add = np.add(arr1,arr2)
print(add)

[ 6  8 10 12]


In [3]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])
sub = arr1 - arr2
print(sub)


[-4 -4 -4 -4]


In [4]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])
mul = arr1 * arr2
print(mul)


[ 5 12 21 32]


In [5]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])
div = arr1 / arr2
print(div)


[0.2        0.33333333 0.42857143 0.5       ]


In [17]:
arr12 = np.array([[1,2,3,4],[1,2,3,4]])
arr22 = np.array([[1,2,3,4],[1,2,3,4]])
print(arr12)
print()
print(arr22)
print()
add2= arr12 + arr22
print(add2)


[[1 2 3 4]
 [1 2 3 4]]

[[1 2 3 4]
 [1 2 3 4]]

[[2 4 6 8]
 [2 4 6 8]]


In [18]:
arr12 = np.array([[1,2,3,4],[1,2,3,4]])
arr22 = np.array([[1,2,3,4],[1,2,3,4]])
print(arr12)
print()
print(arr22)
print()
mul2= arr12 * arr22
print(mul2)

[[1 2 3 4]
 [1 2 3 4]]

[[1 2 3 4]
 [1 2 3 4]]

[[ 1  4  9 16]
 [ 1  4  9 16]]
