In [1]:
import numpy as np

arr1=np.array([1,2,3,4])
arr2=np.array([5,6,7,8])
print(arr1+arr2)

[ 6  8 10 12]


In [5]:
arr1=np.array([1,2,3,4])
print(arr1.shape)  # prints the shape of the array
print(arr1)
print()
arr2=np.array([[1],[2],[3],[4]])
print(arr2.shape)  # prints the shape of the array
print(arr2)

(4,)
[1 2 3 4]

(4, 1)
[[1]
 [2]
 [3]
 [4]]


In [ ]:
print(arr1+arr2)  # Broadcasting happens here
#broadcasting is the process of making arrays with different shapes have compatible shapes for arithmetic operations.

[[2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]
 [5 6 7 8]]


In [7]:
x=np.array([[1,2,3],[4,5,6]])
print(x)
y = np.array([[1],[2]])
print(y)
print(x+y)  # Broadcasting happens here

[[1 2 3]
 [4 5 6]]
[[1]
 [2]]
[[2 3 4]
 [6 7 8]]
