there are 19 datatypes : complex64, int_, intc,etc

In [1]:
import numpy as np
var = np.array([1,2,3])
print("Data Type :",var.dtype)

Data Type : int32


In [2]:
var = np.array([1.0,2.0,3.0])
print("Data Type :",var.dtype)

Data Type : float64


In [3]:
str = np.array(['Nandini','is','a','good'])
print("Data Type :",str.dtype)

Data Type : <U7


In [4]:
str2=np.array(['A','B','C','D'])
print("Data Type :",str2.dtype)

Data Type : <U1


In [5]:
var2 = np.array([1,2,3,'N','B','G'])
print("Data Type :",var2.dtype)

Data Type : <U11


to convert to other datatype

In [8]:
x = np.array([1, 2, 3, 4, 5],dtype='f')
print("Data Type:",x.dtype)
print(x)



Data Type: float32
[1. 2. 3. 4. 5.]


In [ ]:
x2=x.astype('i') #convert to integer 
print("Data Type:",x2.dtype)

Data Type: int32


In [ ]:
x3 = np.array([1,2,3,4,5])
new = np.float32(x3) #convert to float
print("Original Data Type:",x3.dtype)
print("Data Type:",new.dtype)
print(x3)
print(new)


Original Data Type: int32
Data Type: float32
[1 2 3 4 5]
[1. 2. 3. 4. 5.]


In [ ]:
x4=np.array([1.1,2.2,3.3,4.4,5.5])
new2 = np.int_(x4) #convert to integer
print("Original Data Type:",x4.dtype)
print("Data Type:",new2.dtype)
print(x4)
print(new2)

Original Data Type: float64
Data Type: int32
[1.1 2.2 3.3 4.4 5.5]
[1 2 3 4 5]
