Indexing

In [1]:
import numpy as np

arr1 = np.array([1, 2, 3])
print(arr1[1])

2


In [3]:
print(arr1[-1])
print(arr1[-2])
print(arr1[-3])

3
2
1


In [6]:
a1=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(a1)
print()
print(a1.ndim)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

2


In [8]:
print(a1[1,4])#Accessing an element from 2-D array
print(a1[0,2])

10
3


In [9]:
a3 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(a3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [10]:
print(a3.ndim)

3


In [ ]:
print(a3[0,1,2]) #Accessing an element from 3-D array. Here, 0 is the index of 2-D array, 1 is the index of row and 2 is the index of column.

6


Slicing

In [13]:
x=np.array([1,2,3,4,5,6,7,8])
#           0 1 2 3 4 5 6 7
#          -8-7-6-5-4-3-2-1
print(x)

[1 2 3 4 5 6 7 8]


In [14]:
print(x[1:5]) #Slicing from index 1 to 4

[2 3 4 5]


In [15]:
print([x[::2]]) #Slicing with step size of 2

[array([1, 3, 5, 7])]


In [16]:
print(x[-1:-5:-1]) #Slicing in reverse order from index -1 to -4

[8 7 6 5]


In [17]:
print(x[1:])

[2 3 4 5 6 7 8]


In [18]:
print(x[:5])

[1 2 3 4 5]


In [ ]:
print(x[1:5:2])#Slicing with step size of 2.

[2 4]


In [21]:
#two dimensional array slicing
a=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(a)    

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [22]:
print(a[:,1:4]) #Slicing rows and columns from 2-D array. Here, : means all rows and 1:4 means columns from index 1 to 3.

[[2 3 4]
 [7 8 9]]


In [24]:
#3D array slicing
b=np.array([[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]]])
print(b)

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]]


In [25]:
#apply slicing with comments
print(b[1,0,1:3]) #Slicing from 3-D array. Here, 1 is the index of 2-D array, 0 is the index of row and 1:3 means columns from index 1 to 2.    

[10 11]


In [26]:
print(b[0,1,:]) #Slicing from 3-D array. Here, 0 is the index of 2-D array, 1 is the index of row and : means all columns.

[5 6 7 8]
