In [1]:
#Iteration in numpy array is same as in list. break and continue statements can be used in for loop.
#iteration in loop is iterate over each element.

import numpy as np

n = np.array([1,2,3,4,5,6,7,8,9])
print(n)
print()
for i in n:
    print(i)



[1 2 3 4 5 6 7 8 9]

1
2
3
4
5
6
7
8
9


In [5]:
n1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(n1)



[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
print(n1.ndim)

2


In [7]:
for j in n1:
    print(j) #prints each row of 2-D array

[1 2 3]
[4 5 6]
[7 8 9]


In [ ]:
for k in n1: #iterates over each row of 2-D array
    for l in k:#iterates over each element of that row
        print(l) #prints each element of 2-D array

1
2
3
4
5
6
7
8
9


In [11]:
#3d array iteration
n2 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(n2)


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [12]:
print(n2.ndim)

3


In [14]:
for i in n2: #iterates over each 2-D array
    for j in i: #iterates over each row of 2-D array
        for k in j: #iterates over each element of that row
            print(k) #prints each element of 3-D array

1
2
3
4
5
6
7
8
9
10
11
12


In [15]:
#iteration using nditer() is used to iterate over array of any dimension.
#it is faster than normal iteration.
n2 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
for x in np.nditer(n2):
    print(x)

1
2
3
4
5
6
7
8
9
10
11
12


In [ ]:
#use flags and op_dtypes parameters for more control over iteration.
#flags=['buffered'] is used to enable buffering when required.
for x in np.nditer(n2,flags=['buffered'],op_dtypes=['S']): #converts each element to string while iterating
    print(x)

b'1'
b'2'
b'3'
b'4'
b'5'
b'6'
b'7'
b'8'
b'9'
b'10'
b'11'
b'12'


In [19]:
#indexing iteration is used to iterate over every element based on index.
for i,d in np.ndenumerate(n2):
    print(i,d) #prints index and value of each element as tuple

(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 1, 0) 4
(0, 1, 1) 5
(0, 1, 2) 6
(1, 0, 0) 7
(1, 0, 1) 8
(1, 0, 2) 9
(1, 1, 0) 10
(1, 1, 1) 11
(1, 1, 2) 12
