Searching array for a certain value 

In [5]:
import numpy as np
arr1 = np.array([1, 2, 3, 4, 5,2,5,7,3,8,10,3,4,8])
print("Original array:", arr1)
x = np.where(arr1 == 3)
print(x)
print()
x2= np.where(arr1 % 2 == 0)
print(x2)

Original array: [ 1  2  3  4  5  2  5  7  3  8 10  3  4  8]
(array([ 2,  8, 11], dtype=int64),)

(array([ 1,  3,  5,  9, 10, 12, 13], dtype=int64),)


Search sorted array

gives u position to place value in sorted form

In [7]:
arr2 = np.array([6, 7, 9, 9, 10])
print("Original array 2:", arr2)
y = np.searchsorted(arr2,8 )
print(y)

Original array 2: [ 6  7  9  9 10]
2


In [12]:
y2 = np.searchsorted(arr2,[8,4,7,6],'right' )
print("original arr:",arr2)
print()
print(y2)
#side is used to decide if value is to be inserted before or after the rightmost value
# gives u position to place value in sorted form


original arr: [ 6  7  9  9 10]

[2 0 2 1]


Sort array to make array asc

In [13]:
arr3 = np.array([3, 2, 0, 1])
print("original arr3:",arr3)
arr3.sort()
print("sorted arr3:",arr3)

original arr3: [3 2 0 1]
sorted arr3: [0 1 2 3]


In [14]:
str = np.array(['s','a','n','d','i','n','i'])
print("original str arr:",str)
str.sort()
print("sorted str arr:",str)


original str arr: ['s' 'a' 'n' 'd' 'i' 'n' 'i']
sorted str arr: ['a' 'd' 'i' 'i' 'n' 'n' 's']


In [17]:
arr_2d = np.array([[3, 2, 4], [5, 0, 1]])
print("original 2d arr:",arr_2d)
arr_2d.sort()
print("sorted 2d arr :",arr_2d)

original 2d arr: [[3 2 4]
 [5 0 1]]
sorted 2d arr : [[2 3 4]
 [0 1 5]]


Filter : get some val from existing arr and create new arr

In [20]:
b = np.array([41, 42, 43, 44])
filter_arr = np.array([True, False, True, False])
print("original arr b:",b)
newarr = b[filter_arr]
print("new arr:",newarr)
print(type(newarr))

original arr b: [41 42 43 44]
new arr: [41 43]
<class 'numpy.ndarray'>
