Array with filled 0

1 D array

In [1]:
import numpy as np
zero_arr=np.zeros(4)
print(zero_arr)

[0. 0. 0. 0.]


2 D array

In [3]:
import numpy as np
zero2d_arr=np.zeros((3,4))
print(zero2d_arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


ones filled array

In [5]:
ar_ones=np.ones(3)
print(ar_ones)

[1. 1. 1.]


Empty array

In [6]:
ar_em=np.empty(3)
print(ar_em)


[1. 1. 1.]


Range array

In [8]:
arr_range=np.arange(10)
arr_range2=np.arange(3,10)
arr_range3=np.arange(3,10,2)
print(arr_range)
print(arr_range2)
print(arr_range3)

[0 1 2 3 4 5 6 7 8 9]
[3 4 5 6 7 8 9]
[3 5 7 9]


Diagonal array

In [9]:
ar_diag=np.eye(3)
print(ar_diag)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [11]:
ar_dia=np.eye(3,5)
print(ar_dia)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


Linspace

In [ ]:
ar_lin=np.linspace(1,10,5)#5 is no of elements
print(ar_lin)

[ 1.    3.25  5.5   7.75 10.  ]
